# Generated by Django 5.1.2 on 2024-11-06 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_head', models.CharField(max_length=255)),
                ('facility_location', models.CharField(max_length=255)),
                ('facility_description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvac', models.FloatField(default=0.0)),
                ('production', models.FloatField(default=0.0)),
                ('stp_etp', models.FloatField(default=0.0)),
                ('admin_block', models.FloatField(default=0.0)),
                ('utilities', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('fuel_used_in_Operations', models.CharField(choices=[('Types', 'Types'), ('Crude oil - Diesel', 'Crude oil - Diesel'), ('Crude oil - Petrol', 'Crude oil - Petrol'), ('Coal - Cooking coal', 'Coal - Cooking coal'), ('Coal - Coke Oven Coal', 'Coal - Coke Oven Coal'), ('Natural gas', 'Natural gas'), ('Biomass - wood', 'Biomass - wood'), ('Biomass - Other solid waste', 'Biomass - Other solid waste')], default='Types', max_length=255)),
                ('fuel_consumption', models.FloatField(default=0.0)),
                ('renewable_energy_solar', models.FloatField(default=0.0)),
                ('renewable_energy_others', models.FloatField(default=0.0)),
                ('overall_usage', models.FloatField(default=0.0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Biodiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_trees', models.IntegerField(default=0)),
                ('Specie_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('total_area', models.FloatField(default=0.0)),
                ('new_trees_planted', models.FloatField(default=0.0)),
                ('head_count', models.FloatField(default=0.0)),
                ('overall_Trees', models.FloatField(default=0.0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Logistices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logistices_types', models.CharField(choices=[('staff_logistices', 'Staff_Logistices'), ('cargo', 'Cargo')], default='staff_logistices', max_length=255)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('LPG', 'LPG')], default='diesel', max_length=255)),
                ('no_of_trips', models.IntegerField()),
                ('fuel_consumption', models.FloatField(default=0.0)),
                ('no_of_vehicles', models.IntegerField()),
                ('spends_on_fuel', models.FloatField(default=0.0)),
                ('total_fuelconsumption', models.FloatField(default=0.0, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Org_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('business_executive_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('DatePicker', models.DateField(blank=True, null=True)),
                ('food_waste', models.FloatField(default=0.0)),
                ('solid_Waste', models.FloatField(default=0.0)),
                ('E_Waste', models.FloatField(default=0.0)),
                ('Biomedical_waste', models.FloatField(default=0.0)),
                ('liquid_discharge', models.FloatField(default=0.0)),
                ('other_waste', models.FloatField(default=0.0)),
                ('Recycle_waste', models.FloatField(default=0.0)),
                ('Landfill_waste', models.FloatField(default=0.0)),
                ('overall_usage', models.FloatField(default=0.0, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_water', models.FloatField(default=0.0)),
                ('recycled_water', models.FloatField(default=0.0)),
                ('softener_usage', models.FloatField(default=0.0)),
                ('boiler_usage', models.FloatField(default=0.0)),
                ('other_usage', models.FloatField(default=0.0)),
                ('overall_usage', models.FloatField(default=0.0, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
