# Generated by Django 5.1.2 on 2024-11-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='fuel_consumption',
            new_name='biomass_other_solid',
        ),
        migrations.RenameField(
            model_name='energy',
            old_name='fuel_used_in_Operations',
            new_name='fuel_types',
        ),
        migrations.AddField(
            model_name='energy',
            name='biomass_wood',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energy',
            name='coke_oven_coal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energy',
            name='cooking_coal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energy',
            name='diesel',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='energy',
            name='natural_gas',
            field=models.FloatField(default=0.0),
        ),
    ]
