# Generated by Django 5.1.2 on 2024-11-09 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to=settings.AUTH_USER_MODEL),
        ),
    ]
