# Generated by Django 5.1.2 on 2024-11-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
