# Generated by Django 5.1.2 on 2024-11-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
