# Generated by Django 5.1.2 on 2024-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodiversity',
            old_name='Specie_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='biodiversity',
            old_name='no_of_trees',
            new_name='no_trees',
        ),
        migrations.RenameField(
            model_name='biodiversity',
            old_name='total_area',
            new_name='totalArea',
        ),
        migrations.RenameField(
            model_name='energy',
            old_name='renewable_energy_others',
            new_name='renewable_other',
        ),
        migrations.RenameField(
            model_name='energy',
            old_name='renewable_energy_solar',
            new_name='renewable_solar',
        ),
        migrations.RenameField(
            model_name='energy',
            old_name='stp_etp',
            new_name='stp',
        ),
        migrations.RenameField(
            model_name='logistices',
            old_name='no_of_trips',
            new_name='No_Trips',
        ),
        migrations.RenameField(
            model_name='logistices',
            old_name='no_of_vehicles',
            new_name='No_Vehicles',
        ),
        migrations.RenameField(
            model_name='logistices',
            old_name='spends_on_fuel',
            new_name='Spends_on_fuel',
        ),
        migrations.RenameField(
            model_name='logistices',
            old_name='fuel_type',
            new_name='Typeof_fuel',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='boiler_usage',
            new_name='Boiler_usage',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='generated_water',
            new_name='Generated_Water',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='other_usage',
            new_name='otherUsage',
        ),
        migrations.AddField(
            model_name='biodiversity',
            name='DatePicker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biodiversity',
            name='species',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energy',
            name='DatePicker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='energy',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistices',
            name='DatePicker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logistices',
            name='category',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logistices',
            name='km_travelled',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='water',
            name='DatePicker',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='water',
            name='category',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
