# Generated by Django 5.1.2 on 2024-11-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodiversity',
            name='id',
        ),
        migrations.RemoveField(
            model_name='logistices',
            name='id',
        ),
        migrations.AlterField(
            model_name='biodiversity',
            name='biodiversity_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='Typeof_fuel',
            field=models.CharField(choices=[('diesel', 'diesel'), ('petrol', 'petrol')], default='diesel', max_length=255),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='logistices_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='logistices_types',
            field=models.CharField(choices=[('staff_logistices', 'staff_logistices'), ('cargo', 'cargo')], default='staff_logistices', max_length=255),
        ),
    ]
