# Generated by Django 5.1.2 on 2024-10-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='overall_usage',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
