# Generated by Django 5.1.2 on 2024-11-27 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logistices',
            fields=[
                ('category', models.CharField(max_length=255)),
                ('DatePicker', models.DateField(blank=True, null=True)),
                ('logistices_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('logistices_types', models.CharField(choices=[('Staff', 'Staff'), ('Cargo', 'Cargo')], default='staff_logistices', max_length=255)),
                ('Typeof_fuel', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='diesel', max_length=255)),
                ('km_travelled', models.FloatField(default=0.0)),
                ('No_Trips', models.IntegerField()),
                ('fuel_consumption', models.FloatField(default=0.0)),
                ('No_Vehicles', models.IntegerField()),
                ('Spends_on_fuel', models.FloatField(default=0.0)),
                ('total_fuelconsumption', models.FloatField(default=0.0, editable=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Logistics',
        ),
    ]
