# Generated by Django 5.1.2 on 2024-11-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistices',
            name='Typeof_fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol')], default='diesel', max_length=255),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='logistices_types',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Cargo', 'Cargo')], default='staff_logistices', max_length=255),
        ),
    ]
