# Generated by Django 5.1.2 on 2024-11-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistices',
            name='fuel_consumption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('LPG', 'LPG')], default='diesel', max_length=255),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='logistices_types',
            field=models.CharField(choices=[('staff_logistices', 'Staff_Logistices'), ('cargo', 'Cargo')], default='staff_logistices', max_length=255),
        ),
        migrations.AlterField(
            model_name='logistices',
            name='spends_on_fuel',
            field=models.FloatField(default=0.0),
        ),
    ]
