# Generated by Django 5.1.2 on 2024-10-22 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_waste', models.FloatField(default=0.0)),
                ('solid_waste', models.FloatField(default=0.0)),
                ('e_waste', models.FloatField(default=0.0)),
                ('biomedical_waste', models.FloatField(default=0.0)),
                ('liquid_discharge', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('sent_for_recycle', models.FloatField(default=0.0)),
                ('send_to_landfill', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
