# Generated by Django 5.1.2 on 2024-11-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energy',
            old_name='cooking_coal',
            new_name='coking_coal',
        ),
    ]
