# Generated by Django 5.1.2 on 2024-10-29 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logistices',
            name='fuel_type',
            field=models.CharField(choices=[('type', 'Type'), ('diesel', 'Diesel'), ('petrol', 'Petrol'), ('LPG', 'LPG')], default='type', max_length=255),
        ),
        migrations.CreateModel(
            name='Org_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_org', models.CharField(max_length=255)),
                ('name_of_bussiness_exe', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('branch_id', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
