# Generated by Django 5.1.2 on 2024-11-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0002_alter_facility_facility_id_alter_waste_waste_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='id',
        ),
        migrations.AlterField(
            model_name='energy',
            name='energy_id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
