# Generated by Django 5.1.2 on 2024-11-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0002_rename_specie_name_biodiversity_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_registration',
            old_name='branch_id',
            new_name='Branch_ID',
        ),
        migrations.RenameField(
            model_name='org_registration',
            old_name='business_executive_name',
            new_name='Business_executive_Name',
        ),
        migrations.RenameField(
            model_name='org_registration',
            old_name='location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='org_registration',
            old_name='organization_name',
            new_name='Organization_Name',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='recycled_water',
            new_name='Recycled_Water',
        ),
        migrations.RenameField(
            model_name='water',
            old_name='softener_usage',
            new_name='Softener_usage',
        ),
    ]
