# Generated by Django 5.1.2 on 2024-10-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0002_alter_logistices_fuel_type_org_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_registration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
