# Generated by Django 5.1.2 on 2024-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0002_waste_overall_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='energy',
            name='fuel_used_in_Operations',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energy',
            name='overall_usage',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
