# Generated by Django 5.1.2 on 2024-10-22 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0002_waste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hvac', models.FloatField(default=0.0)),
                ('production', models.FloatField(default=0.0)),
                ('stp_etp', models.FloatField(default=0.0)),
                ('admin_block', models.FloatField(default=0.0)),
                ('utilities', models.FloatField(default=0.0)),
                ('others', models.FloatField(default=0.0)),
                ('renewable_energy_solar', models.FloatField(default=0.0)),
                ('renewable_energy_others', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
