# Generated by Django 5.1.2 on 2024-10-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0003_energy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_head', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Biodiversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_trees', models.IntegerField()),
                ('Specie_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Water', 'Water'), ('Energy', 'Energy'), ('Waste', 'Waste'), ('Biodiversity', 'Biodiversity'), ('Logistics', 'Logistics')], max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_pzc.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_water', models.FloatField(default=0.0)),
                ('recycled_water', models.FloatField(default=0.0)),
                ('softener_usage', models.FloatField(default=0.0)),
                ('boiler_usage', models.FloatField(default=0.0)),
                ('other_usage', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
