# Generated by Django 5.1.2 on 2024-10-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0003_alter_org_registration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_registration',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
