# Generated by Django 5.1.2 on 2024-10-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0003_energy_fuel_used_in_operations_energy_overall_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversity',
            name='overall_Trees',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
