# Generated by Django 5.1.2 on 2024-10-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0004_alter_org_registration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_registration',
            name='location',
            field=models.CharField(default='Unknown Locations', max_length=255),
        ),
    ]
