# Generated by Django 5.1.2 on 2024-10-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_pzc', '0005_alter_org_registration_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_registration',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
