# Generated by Django 5.1.2 on 2024-12-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('Summary', 'Summary'), ('Brief Summary', 'Brief Summary')], max_length=50)),
                ('financial_year', models.CharField(max_length=9)),
                ('category', models.CharField(choices=[('Water', 'Water'), ('Energy', 'Energy'), ('Waste', 'Waste'), ('Biodiversity', 'Biodiversity'), ('Logistics', 'Logistics')], max_length=50)),
                ('add_summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('organisation_name', models.CharField(max_length=255)),
                ('business_executive', models.CharField(max_length=255)),
                ('cin_number', models.CharField(max_length=20)),
                ('year_of_corporation', models.IntegerField(blank=True, default=2024, null=True)),
                ('website_url', models.URLField()),
                ('corporate_address', models.TextField()),
                ('registered_office_address', models.TextField()),
                ('reporting_boundary', models.CharField(max_length=255)),
                ('DatePicker', models.DateField(blank=True, null=True)),
                ('contact_no', models.CharField(max_length=15)),
                ('alternative_contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
