# Generated by Django 5.1.2 on 2024-12-05 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_registration', '0001_initial'),
        ('users_pzc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_summaries', to='users_pzc.facility'),
        ),
        migrations.AddField(
            model_name='summary',
            name='organisation',
            field=models.ForeignKey(limit_choices_to={'role': 'user'}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
