# Generated by Django 5.1.2 on 2024-12-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_registration', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='category',
            field=models.CharField(blank=True, choices=[('Water', 'Water'), ('Energy', 'Energy'), ('Waste', 'Waste'), ('Biodiversity', 'Biodiversity'), ('Logistics', 'Logistics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='summary_type',
            field=models.CharField(choices=[('Summary', 'Summary'), ('Brief Summary', 'Brief Summary'), ('Long Summary', 'Load Summary')], max_length=50),
        ),
    ]
